const APP = {};

APP.WEATHER_API = 'https://zgis185.geo.sbg.ac.at/group04/api/weather';
APP.WEATHER_24H = 'https://zgis185.geo.sbg.ac.at/group04/api/weather/24h';

APP.WFS = {
  studyArea: 'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=ipsdi_st26:study_area&maxFeatures=50&outputFormat=application/json',
  nuts:      'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=ipsdi_st26:civis_nuts&maxFeatures=50&outputFormat=application/json',
  cities:    'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=ipsdi_st26:civis_cities&maxFeatures=50&outputFormat=application/json',
plantaeSalzburg: 'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=ipsdi_st26:SalburgPlantae_Export_s1104190&outputFormat=application/json',};

APP.WMS_CONFIG = {
  lst2022:   { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:LST2022',   opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  lst2025:   { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:LST2025',   opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  uhi2022:   { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:UHI2022',   opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  uhi2025:   { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:UHI2025',   opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  utfvi2022: { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:UTFVI2022', opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  utfvi2025: { url:'https://geoserver22s.zgis.at/geoserver/ipsdi_st26/wms', layer:'ipsdi_st26:UTFVI2025', opts:{version:'1.1.0',transparent:true,format:'image/png',attribution:'© Z_GIS PLUS Salzburg'} },
  lu:    { url:'https://image.discomap.eea.europa.eu/arcgis/services/UrbanAtlas/UA_UrbanAtlas_2018/MapServer/WMSServer', layer:'Land_Use_vector52160',  opts:{version:'1.3.0',transparent:true,format:'image/png'} },
  trees: { url:'https://image.discomap.eea.europa.eu/arcgis/services/UrbanAtlas/UA_StreetTreeLayer_2018/MapServer/WMSServer', layer:'STL_2018_Vector43148', opts:{version:'1.3.0',transparent:true,format:'image/png',uppercase:true} },
  imp: { url:'https://image.discomap.eea.europa.eu/arcgis/services/GioLandPublic/HRL_ImperviousnessDensity_2018/ImageServer/WMSServer', layer:'HRL_ImperviousnessDensity_2018', opts:{version:'1.3.0',transparent:true,format:'image/png'} },

APP.YEAR_LAYERS = {
  lst:   { '2022':'lst2022',   '2025':'lst2025'   },
  uhi:   { '2022':'uhi2022',   '2025':'uhi2025'   },
  utfvi: { '2022':'utfvi2022', '2025':'utfvi2025' },
};

APP.CITIES = {
  marseille: { label:'Aix-en-Provence & Marseille, FR', wxCity:'Marseille', nuts3:'FRL04', tz:'Europe/Paris',    center:[43.2965,5.3698],  zoom:11, lst:35.8, uhi:2.4, utfvi:'Strong',  land:'Discontinuous urban', green:22, imp:50, pop:877215  },
  athens:    { label:'Athens, GR',                      wxCity:'Athens',    nuts3:'EL303', tz:'Europe/Athens',   center:[37.9838,23.7275], zoom:12, lst:39.2, uhi:4.1, utfvi:'Extreme', land:'Continuous urban',    green:12, imp:68, pop:643452  },
  bucharest: { label:'Bucharest, RO',                   wxCity:'Bucharest', nuts3:'RO321', tz:'Europe/Bucharest',center:[44.4268,26.1025], zoom:11, lst:36.2, uhi:2.6, utfvi:'Strong',  land:'Urban fabric',        green:18, imp:58, pop:2142929 },
  brussels:  { label:'Brussels, BE',                    wxCity:'Brussels',  nuts3:'BE100', tz:'Europe/Brussels', center:[50.8503,4.3517],  zoom:12, lst:31.4, uhi:1.9, utfvi:'Moderate',land:'Continuous urban',    green:24, imp:52, pop:1222637 },
  glasgow:   { label:'Glasgow, UK',                     wxCity:'Glasgow',   nuts3:'UKM82', tz:'Europe/London',   center:[55.8642,-4.2518], zoom:11, lst:28.6, uhi:1.4, utfvi:'Moderate',land:'Discontinuous urban', green:32, imp:38, pop:null    },
  lausanne:  { label:'Lausanne, CH',                    wxCity:'Geneva',    nuts3:'CH011', tz:'Europe/Zurich',   center:[46.5197,6.6323],  zoom:12, lst:29.8, uhi:1.6, utfvi:'Moderate',land:'Discontinuous urban', green:38, imp:35, pop:null    },
  madrid:    { label:'Madrid, ES',                      wxCity:'Madrid',    nuts3:'ES300', tz:'Europe/Madrid',   center:[40.4168,-3.7038], zoom:10, lst:37.1, uhi:3.4, utfvi:'Extreme', land:'Continuous urban',    green:15, imp:62, pop:3255944 },
  rome:      { label:'Rome, IT',                        wxCity:'Rome',      nuts3:'ITI43', tz:'Europe/Rome',     center:[41.9028,12.4964], zoom:11, lst:38.5, uhi:3.1, utfvi:'Strong',  land:'Continuous urban',    green:20, imp:55, pop:2761632 },
  salzburg:  { label:'Salzburg, AT',                    wxCity:'Salzburg',  nuts3:'AT323', tz:'Europe/Vienna',   center:[47.8095,13.0432], zoom:12, lst:30.2, uhi:1.5, utfvi:'Moderate',land:'Discontinuous urban', green:40, imp:32, pop:157245  },
  stockholm: { label:'Stockholm, SE',                   wxCity:'Stockholm', nuts3:'SE110', tz:'Europe/Stockholm',center:[59.3293,18.0686], zoom:11, lst:26.8, uhi:1.2, utfvi:'Weak',    land:'Discontinuous urban', green:45, imp:30, pop:1689945 },
  tuebingen: { label:'Tubingen, DE',                    wxCity:'Stuttgart', nuts3:'DE142', tz:'Europe/Berlin',   center:[48.5216,9.0576],  zoom:12, lst:32.4, uhi:1.7, utfvi:'Moderate',land:'Discontinuous urban', green:36, imp:36, pop:83416   },
};

APP.CITY_KEYS   = Object.keys(APP.CITIES);
APP.CITY_LABELS = APP.CITY_KEYS.map(k => APP.CITIES[k].label.split(',')[0]);

APP.GREENNESS = {
  marseille:0.24, athens:0.12, bucharest:0.31, brussels:0.30,
  glasgow:null, lausanne:null, madrid:0.19, rome:0.30,
  salzburg:0.48, stockholm:0.31, tuebingen:0.49,
};

APP.LV = { lst:false, uhi:true, utfvi:false, gbif:false, trees:false, lu:false, imp:false, study:true, nuts:true };

APP.I18N = {
  en: { HEAT_ANALYSIS:'HEAT ANALYSIS', BIODIVERSITY:'BIODIVERSITY', URBAN_ATLAS:'URBAN ATLAS / LAND USE', REFERENCE:'REFERENCE', BASEMAP:'BASEMAP', lst:'LST (°C)', uhi:'UHI index', utfvi:'UTFVI class', n2k:'Natura 2000', gbif:'Species density', trees:'Street trees', green:'Green spaces', lu:'Land use 2018', imp:'Impervious surf.', study:'Study area', nuts:'NUTS3 boundary', analytics:'Analytics', legend:'Legend', click_map:'Click map to inspect', feature_info:'Feature info', live_weather:'Live weather (METAR)', temperature:'Temperature', dew_point:'Dew point', wind:'Wind', observed:'Observed', land_use:'Land use', select_city:'Select CIVIS city (11)…', ch_trend:'24h temperature trend — live METAR data', ch_pop:'Population — all CIVIS cities', ch_green:'Greenness index — all CIVIS cities', ob_t1:'Select a city', ob_t2:'Toggle layers', ob_t3:'Click the map', ob_t4:'Open Analytics', ob_t5:'Export data', ob_d1:'Use the dropdown to pick one of the 11 CIVIS alliance cities. The map flies there instantly.', ob_d2:'The left panel controls all map layers. Activate LST, UHI and UTFVI to see heat patterns. Add biodiversity and land use to understand the drivers.', ob_d3:'Click anywhere on the map to inspect feature values — LST, UHI, land use class and live METAR weather.', ob_d4:'Click the Analytics button to compare all 11 cities — 24h trend, population, and greenness index.', ob_d5:'Use PDF, GeoJSON and CSV to export data. Every layer has a Metadata download button.', skip:'Skip', next:'Next', get_started:'Get started', sources:'Sources', about:'About', lst_short:'LST', uhi_much_cooler:'much cooler', uhi_cooler:'cooler', uhi_slightly_warmer:'slightly warmer', uhi_warmer:'warmer', uhi_much_warmer:'much warmer', utfvi_none:'none', utfvi_weak:'weak', utfvi_middle:'middle', utfvi_strong:'strong', utfvi_stronger:'stronger', utfvi_strongest:'strongest', data_sources:'Data Sources', version:'Version', updated:'Updated', course:'Course', institution:'Institution', supervisor:'Supervisor', team:'Team', description:'Description', replay_tutorial:'Replay tutorial', src_heat:'Heat Analysis (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Boundaries (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Land Use & Vegetation (Copernicus / EEA)', src_stats:'Statistics & Weather', src_ai:'AI Assistance', src_libs:'Libraries & Tools' },
  de: { HEAT_ANALYSIS:'WÄRMEANALYSE', BIODIVERSITY:'BIODIVERSITÄT', URBAN_ATLAS:'URBANER ATLAS / LANDNUTZUNG', REFERENCE:'REFERENZ', BASEMAP:'GRUNDKARTE', lst:'OFT (°C)', uhi:'UHI-Index', utfvi:'UTFVI-Klasse', n2k:'Natura 2000', gbif:'Artendichte', trees:'Straßenbäume', green:'Grünflächen', lu:'Landnutzung 2018', imp:'Versiegelte Flächen', study:'Untersuchungsgebiet', nuts:'NUTS3-Grenze', analytics:'Analytik', legend:'Legende', click_map:'Karte anklicken', feature_info:'Attributinfo', live_weather:'Livewetter (METAR)', temperature:'Temperatur', dew_point:'Taupunkt', wind:'Wind', observed:'Beobachtet', land_use:'Landnutzung', select_city:'CIVIS-Stadt wählen (11)…', ch_trend:'24h Temperaturverlauf — Live METAR-Daten', ch_pop:'Bevölkerung — alle CIVIS-Städte', ch_green:'Grünheitsindex — alle CIVIS-Städte', ob_t1:'Stadt auswählen', ob_t2:'Ebenen umschalten', ob_t3:'Karte anklicken', ob_t4:'Analytik öffnen', ob_t5:'Daten exportieren', ob_d1:'Wählen Sie eine der 11 CIVIS-Allianzstädte aus dem Dropdown.', ob_d2:'Das linke Panel steuert alle Kartenebenen. Aktivieren Sie OFT, UHI und UTFVI für Wärmemuster.', ob_d3:'Klicken Sie auf die Karte, um Werte abzufragen.', ob_d4:'Klicken Sie auf Analytik, um alle 11 Städte zu vergleichen.', ob_d5:'Nutzen Sie PDF, GeoJSON und CSV zum Exportieren.', skip:'Überspringen', next:'Weiter', get_started:'Loslegen', sources:'Quellen', about:'Über', lst_short:'OFT', uhi_much_cooler:'viel kühler', uhi_cooler:'kühler', uhi_slightly_warmer:'leicht wärmer', uhi_warmer:'wärmer', uhi_much_warmer:'viel wärmer', utfvi_none:'keine', utfvi_weak:'schwach', utfvi_middle:'mittel', utfvi_strong:'stark', utfvi_stronger:'stärker', utfvi_strongest:'am stärksten', data_sources:'Datenquellen', version:'Version', updated:'Aktualisiert', course:'Kurs', institution:'Institution', supervisor:'Betreuer', team:'Team', description:'Beschreibung', replay_tutorial:'Tutorial wiederholen', src_heat:'Wärmeanalyse (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Grenzen (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Landnutzung & Vegetation (Copernicus / EEA)', src_stats:'Statistik & Wetter', src_ai:'KI-Unterstützung', src_libs:'Bibliotheken & Werkzeuge' },
  fr: { HEAT_ANALYSIS:'ANALYSE THERMIQUE', BIODIVERSITY:'BIODIVERSITÉ', URBAN_ATLAS:'ATLAS URBAIN / OCCUPATION DU SOL', REFERENCE:'RÉFÉRENCE', BASEMAP:'FOND DE CARTE', lst:'TSS (°C)', uhi:'Indice UHI', utfvi:'Classe UTFVI', n2k:'Natura 2000', gbif:'Densité d\'espèces', trees:'Arbres urbains', green:'Espaces verts', lu:'Occupation du sol 2018', imp:'Surfaces imp.', study:'Zone d\'étude', nuts:'Limite NUTS3', analytics:'Analytique', legend:'Légende', click_map:'Cliquer sur la carte', feature_info:'Info attributs', live_weather:'Météo en direct (METAR)', temperature:'Température', dew_point:'Point de rosée', wind:'Vent', observed:'Observé', land_use:'Occupation du sol', select_city:'Sélectionner une ville CIVIS (11)…', ch_trend:'Tendance 24h — données METAR', ch_pop:'Population — toutes les villes CIVIS', ch_green:'Indice de verdure — toutes les villes CIVIS', ob_t1:'Sélectionner une ville', ob_t2:'Basculer les couches', ob_t3:'Cliquer sur la carte', ob_t4:'Ouvrir l\'analytique', ob_t5:'Exporter les données', ob_d1:'Utilisez le menu déroulant pour choisir une ville CIVIS.', ob_d2:'Le panneau gauche contrôle toutes les couches.', ob_d3:'Cliquez sur la carte pour inspecter les valeurs.', ob_d4:'Cliquez sur Analytique pour comparer les 11 villes.', ob_d5:'Utilisez PDF, GeoJSON et CSV pour exporter.', skip:'Passer', next:'Suivant', get_started:'Commencer', sources:'Sources', about:'À propos', lst_short:'TSS', uhi_much_cooler:'beaucoup plus frais', uhi_cooler:'plus frais', uhi_slightly_warmer:'légèrement plus chaud', uhi_warmer:'plus chaud', uhi_much_warmer:'beaucoup plus chaud', utfvi_none:'aucun', utfvi_weak:'faible', utfvi_middle:'moyen', utfvi_strong:'fort', utfvi_stronger:'plus fort', utfvi_strongest:'le plus fort', data_sources:'Sources de données', version:'Version', updated:'Mis à jour', course:'Cours', institution:'Institution', supervisor:'Superviseur', team:'Équipe', description:'Description', replay_tutorial:'Revoir le tutoriel', src_heat:'Analyse thermique (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Limites (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Occupation du sol & végétation (Copernicus / EEA)', src_stats:'Statistiques & météo', src_ai:'Assistance IA', src_libs:'Bibliothèques & outils' },
  es: { HEAT_ANALYSIS:'ANÁLISIS TÉRMICO', BIODIVERSITY:'BIODIVERSIDAD', URBAN_ATLAS:'ATLAS URBANO / USO DEL SUELO', REFERENCE:'REFERENCIA', BASEMAP:'MAPA BASE', lst:'LST (°C)', uhi:'Índice UHI', utfvi:'Clase UTFVI', n2k:'Natura 2000', gbif:'Densidad de especies', trees:'Árboles urbanos', green:'Espacios verdes', lu:'Uso del suelo 2018', imp:'Sup. impermeable', study:'Área de estudio', nuts:'Límite NUTS3', analytics:'Analítica', legend:'Leyenda', click_map:'Haga clic en el mapa', feature_info:'Información', live_weather:'Tiempo en vivo (METAR)', temperature:'Temperatura', dew_point:'Punto de rocío', wind:'Viento', observed:'Observado', land_use:'Uso del suelo', select_city:'Seleccionar ciudad CIVIS (11)…', ch_trend:'Tendencia 24h — datos METAR', ch_pop:'Población — todas las ciudades CIVIS', ch_green:'Índice de verdor — todas las ciudades CIVIS', ob_t1:'Seleccionar una ciudad', ob_t2:'Activar capas', ob_t3:'Hacer clic en el mapa', ob_t4:'Abrir analítica', ob_t5:'Exportar datos', ob_d1:'Use el menú para elegir una ciudad CIVIS.', ob_d2:'El panel izquierdo controla todas las capas.', ob_d3:'Haga clic en el mapa para inspeccionar valores.', ob_d4:'Haga clic en Analítica para comparar las 11 ciudades.', ob_d5:'Use PDF, GeoJSON y CSV para exportar.', skip:'Saltar', next:'Siguiente', get_started:'Empezar', sources:'Fuentes', about:'Acerca de', lst_short:'LST', uhi_much_cooler:'mucho más frío', uhi_cooler:'más frío', uhi_slightly_warmer:'ligeramente más cálido', uhi_warmer:'más cálido', uhi_much_warmer:'mucho más cálido', utfvi_none:'ninguno', utfvi_weak:'débil', utfvi_middle:'medio', utfvi_strong:'fuerte', utfvi_stronger:'más fuerte', utfvi_strongest:'el más fuerte', data_sources:'Fuentes de datos', version:'Versión', updated:'Actualizado', course:'Curso', institution:'Institución', supervisor:'Supervisor', team:'Equipo', description:'Descripción', replay_tutorial:'Repetir tutorial', src_heat:'Análisis térmico (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Límites (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Uso del suelo y vegetación (Copernicus / EEA)', src_stats:'Estadísticas y clima', src_ai:'Asistencia de IA', src_libs:'Bibliotecas y herramientas' },
  it: { HEAT_ANALYSIS:'ANALISI TERMICA', BIODIVERSITY:'BIODIVERSITÀ', URBAN_ATLAS:'ATLANTE URBANO / USO DEL SUOLO', REFERENCE:'RIFERIMENTO', BASEMAP:'MAPPA BASE', lst:'LST (°C)', uhi:'Indice UHI', utfvi:'Classe UTFVI', n2k:'Natura 2000', gbif:'Densità specie', trees:'Alberi urbani', green:'Spazi verdi', lu:'Uso del suolo 2018', imp:'Sup. impermeabile', study:'Area di studio', nuts:'Confine NUTS3', analytics:'Analisi', legend:'Legenda', click_map:'Clicca sulla mappa', feature_info:'Informazioni', live_weather:'Meteo in diretta (METAR)', temperature:'Temperatura', dew_point:'Punto di rugiada', wind:'Vento', observed:'Osservato', land_use:'Uso del suolo', select_city:'Seleziona città CIVIS (11)…', ch_trend:'Tendenza 24h — dati METAR', ch_pop:'Popolazione — tutte le città CIVIS', ch_green:'Indice di verdure — tutte le città CIVIS', ob_t1:'Seleziona una città', ob_t2:'Attiva livelli', ob_t3:'Clicca sulla mappa', ob_t4:'Apri analisi', ob_t5:'Esporta dati', ob_d1:'Usa il menu per scegliere una città CIVIS.', ob_d2:'Il pannello sinistro controla tutti i livelli.', ob_d3:'Clicca sulla mappa per ispezionare valori.', ob_d4:'Clicca su Analisi per confrontare le 11 città.', ob_d5:'Usa PDF, GeoJSON e CSV per esportare.', skip:'Salta', next:'Avanti', get_started:'Inizia', sources:'Fonti', about:'Info', lst_short:'LST', uhi_much_cooler:'molto più fresco', uhi_cooler:'più fresco', uhi_slightly_warmer:'leggermente più caldo', uhi_warmer:'più caldo', uhi_much_warmer:'molto più caldo', utfvi_none:'nessuno', utfvi_weak:'debole', utfvi_middle:'medio', utfvi_strong:'forte', utfvi_stronger:'più forte', utfvi_strongest:'il più forte', data_sources:'Fonti dati', version:'Versione', updated:'Aggiornato', course:'Corso', institution:'Istituzione', supervisor:'Supervisore', team:'Squadra', description:'Descrizione', replay_tutorial:'Rivedi il tutorial', src_heat:'Analisi termica (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Confini (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Uso del suolo e vegetazione (Copernicus / EEA)', src_stats:'Statistiche e meteo', src_ai:'Assistenza IA', src_libs:'Librerie e strumenti' },
  sv: { HEAT_ANALYSIS:'VÄRMEANALYS', BIODIVERSITY:'BIOLOGISK MÅNGFALD', URBAN_ATLAS:'STADSATLAS / MARKANVÄNDNING', REFERENCE:'REFERENS', BASEMAP:'GRUNDKARTA', lst:'LST (°C)', uhi:'UHI-index', utfvi:'UTFVI-klass', n2k:'Natura 2000', gbif:'Artdensitet', trees:'Gatutrad', green:'Grönområden', lu:'Markanvändning 2018', imp:'Imp. ytor', study:'Studieområde', nuts:'NUTS3-gräns', analytics:'Analys', legend:'Teckenförklaring', click_map:'Klicka på kartan', feature_info:'Objektinfo', live_weather:'Livevader (METAR)', temperature:'Temperatur', dew_point:'Daggpunkt', wind:'Vind', observed:'Observerad', land_use:'Markanvändning', select_city:'Välj CIVIS-stad (11)…', ch_trend:'24h temperaturtrend — live METAR', ch_pop:'Befolkning — alla CIVIS-städer', ch_green:'Grönindex — alla CIVIS-städer', ob_t1:'Välj en stad', ob_t2:'Växla lager', ob_t3:'Klicka på kartan', ob_t4:'Öppna analys', ob_t5:'Exportera data', ob_d1:'Använd menyn för att välja en CIVIS-stad.', ob_d2:'Vänster panelen styr alla kartlager.', ob_d3:'Klicka på kartan för att inspektera värden.', ob_d4:'Klicka på Analys för att jämföra städerna.', ob_d5:'Använd PDF, GeoJSON och CSV för export.', skip:'Hoppa över', next:'Nästa', get_started:'Börja', sources:'Källor', about:'Om', lst_short:'LST', uhi_much_cooler:'mycket svalare', uhi_cooler:'svalare', uhi_slightly_warmer:'något varmare', uhi_warmer:'varmare', uhi_much_warmer:'mycket varmare', utfvi_none:'ingen', utfvi_weak:'svag', utfvi_middle:'medel', utfvi_strong:'stark', utfvi_stronger:'starkare', utfvi_strongest:'starkast', data_sources:'Datakällor', version:'Version', updated:'Uppdaterad', course:'Kurs', institution:'Institution', supervisor:'Handledare', team:'Team', description:'Beskrivning', replay_tutorial:'Spela upp handledning igen', src_heat:'Värmeanalys (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Gränser (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Markanvändning & vegetation (Copernicus / EEA)', src_stats:'Statistik & väder', src_ai:'AI-assistans', src_libs:'Bibliotek & verktyg' },
  nl: { HEAT_ANALYSIS:'HITTEANALYSE', BIODIVERSITY:'BIODIVERSITEIT', URBAN_ATLAS:'STADSATLAS / LANDGEBRUIK', REFERENCE:'REFERENTIE', BASEMAP:'BASISKAART', lst:'LST (°C)', uhi:'UHI-index', utfvi:'UTFVI-klasse', n2k:'Natura 2000', gbif:'Soortendichtheid', trees:'Straatbomen', green:'Groene ruimten', lu:'Landgebruik 2018', imp:'Ondoorlatende opp.', study:'Studiegebied', nuts:'NUTS3-grens', analytics:'Analyse', legend:'Legenda', click_map:'Klik op de kaart', feature_info:'Objectinfo', live_weather:'Liveweer (METAR)', temperature:'Temperatuur', dew_point:'Dauwpunt', wind:'Wind', observed:'Waargenomen', land_use:'Landgebruik', select_city:'Kies CIVIS-stad (11)…', ch_trend:'24u temperatuurtrend — live METAR', ch_pop:'Bevolking — alle CIVIS-steden', ch_green:'Groenindex — alle CIVIS-steden', ob_t1:'Selecteer een stad', ob_t2:'Lagen in-/uitschakelen', ob_t3:'Klik op de kaart', ob_t4:'Open analyse', ob_t5:'Exporteer data', ob_d1:'Gebruik het menu om een CIVIS-stad te kiezen.', ob_d2:'Het linkerpaneel beheert alle kaartlagen.', ob_d3:'Klik op de kaart om waarden te bekijken.', ob_d4:'Klik op Analyse om steden te vergelijken.', ob_d5:'Gebruik PDF, GeoJSON en CSV voor export.', skip:'Overslaan', next:'Volgende', get_started:'Aan de slag', sources:'Bronnen', about:'Over', lst_short:'LST', uhi_much_cooler:'veel koeler', uhi_cooler:'koeler', uhi_slightly_warmer:'iets warmer', uhi_warmer:'warmer', uhi_much_warmer:'veel warmer', utfvi_none:'geen', utfvi_weak:'zwak', utfvi_middle:'gemiddeld', utfvi_strong:'sterk', utfvi_stronger:'sterker', utfvi_strongest:'sterkst', data_sources:'Gegevensbronnen', version:'Versie', updated:'Bijgewerkt', course:'Cursus', institution:'Instelling', supervisor:'Begeleider', team:'Team', description:'Beschrijving', replay_tutorial:'Tutorial herhalen', src_heat:'Hitteanalyse (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Grenzen (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Landgebruik & vegetatie (Copernicus / EEA)', src_stats:'Statistiek & weer', src_ai:'AI-ondersteuning', src_libs:'Bibliotheken & tools' },
  ro: { HEAT_ANALYSIS:'ANALIZĂ TERMICĂ', BIODIVERSITY:'BIODIVERSITATE', URBAN_ATLAS:'ATLAS URBAN / UTILIZARE TEREN', REFERENCE:'REFERINȚĂ', BASEMAP:'HARTĂ DE BAZĂ', lst:'LST (°C)', uhi:'Indice UHI', utfvi:'Clasă UTFVI', n2k:'Natura 2000', gbif:'Densitate specii', trees:'Arbori stradali', green:'Spații verzi', lu:'Utilizare teren 2018', imp:'Supr. impermeabilă', study:'Zona de studiu', nuts:'Limita NUTS3', analytics:'Analiză', legend:'Legendă', click_map:'Faceți clic pe hartă', feature_info:'Informații', live_weather:'Vreme în direct (METAR)', temperature:'Temperatură', dew_point:'Punct de rouă', wind:'Vânt', observed:'Observat', land_use:'Utilizare teren', select_city:'Selectați orașul CIVIS (11)…', ch_trend:'Tendință 24h — date METAR', ch_pop:'Populație — toate orașele CIVIS', ch_green:'Indice de verdeață — toate orașele CIVIS', ob_t1:'Selectați un oraș', ob_t2:'Comutați straturile', ob_t3:'Faceți clic pe hartă', ob_t4:'Deschideți analiza', ob_t5:'Exportați datele', ob_d1:'Folosiți meniul pentru a alege un oraș CIVIS.', ob_d2:'Panoul din stânga controlează straturile hărții.', ob_d3:'Faceți clic pe hartă pentru a inspecta valorile.', ob_d4:'Faceți clic pe Analiză pentru a compara orașele.', ob_d5:'Folosiți PDF, GeoJSON și CSV pentru export.', skip:'Omiteți', next:'Următorul', get_started:'Start', sources:'Surse', about:'Despre', lst_short:'LST', uhi_much_cooler:'mult mai rece', uhi_cooler:'mai rece', uhi_slightly_warmer:'puțin mai cald', uhi_warmer:'mai cald', uhi_much_warmer:'mult mai cald', utfvi_none:'niciuna', utfvi_weak:'slabă', utfvi_middle:'medie', utfvi_strong:'puternică', utfvi_stronger:'mai puternică', utfvi_strongest:'cea mai puternică', data_sources:'Surse de date', version:'Versiune', updated:'Actualizat', course:'Curs', institution:'Instituție', supervisor:'Supervizor', team:'Echipă', description:'Descriere', replay_tutorial:'Reluați tutorialul', src_heat:'Analiză termică (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Limite (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Utilizare teren & vegetație (Copernicus / EEA)', src_stats:'Statistici & vreme', src_ai:'Asistență IA', src_libs:'Biblioteci & instrumente' },
  el: { HEAT_ANALYSIS:'ΘΕΡΜΙΚΗ ΑΝΑΛΥΣΗ', BIODIVERSITY:'ΒΙΟΠΟΙΚΙΛΟΤΗΤΑ', URBAN_ATLAS:'ΑΣΤΙΚΟΣ ΧΑΡΤΗΣ', REFERENCE:'ΑΝΑΦΟΡΑ', BASEMAP:'ΥΠΟΒΑΘΡΟ', lst:'LST (°C)', uhi:'Δείκτης UHI', utfvi:'Κλάση UTFVI', n2k:'Natura 2000', gbif:'Πυκνότητα ειδών', trees:'Δένδρα οδών', green:'Χώροι πρασίνου', lu:'Χρήση γης 2018', imp:'Αδιαπέρατες', study:'Περιοχή μελέτης', nuts:'Όριο NUTS3', analytics:'Αναλυτικά', legend:'Υπόμνημα', click_map:'Κλικ στον χάρτη', feature_info:'Πληροφορίες', live_weather:'Ζωντανός καιρός', temperature:'Θερμοκρασία', dew_point:'Σημείο δρόσου', wind:'Άνεμος', observed:'Παρατηρήθηκε', land_use:'Χρήση γης', select_city:'Επιλέξτε πόλη CIVIS…', ch_trend:'24h τάση θερμοκρασίας', ch_pop:'Πληθυσμός — όλες οι πόλεις CIVIS', ch_green:'Δείκτης πρασίνου', ob_t1:'Επιλογή πόλης', ob_t2:'Εναλλαγή επιπέδων', ob_t3:'Κλικ στον χάρτη', ob_t4:'Ανοίξτε αναλυτικά', ob_t5:'Εξαγωγή δεδομένων', ob_d1:'Χρησιμοποιήστε το μενού για να επιλέξετε μία πόλη CIVIS.', ob_d2:'Το αριστερό πάνελ ελέγχει όλα τα επίπεδα.', ob_d3:'Κλικάρετε στον χάρτη για να επιθεωρήσετε τιμές.', ob_d4:'Κλικάρετε στα Αναλυτικά για σύγκριση.', ob_d5:'Χρησιμοποιήστε PDF, GeoJSON και CSV.', skip:'Παράλειψη', next:'Επόμενο', get_started:'Εκκίνηση', sources:'Πηγές', about:'Σχετικά', lst_short:'LST', uhi_much_cooler:'πολύ πιο δροσερό', uhi_cooler:'πιο δροσερό', uhi_slightly_warmer:'ελαφρώς θερμότερο', uhi_warmer:'θερμότερο', uhi_much_warmer:'πολύ θερμότερο', utfvi_none:'καμία', utfvi_weak:'ασθενής', utfvi_middle:'μέτρια', utfvi_strong:'ισχυρή', utfvi_stronger:'ισχυρότερη', utfvi_strongest:'η ισχυρότερη', data_sources:'Πηγές δεδομένων', version:'Έκδοση', updated:'Ενημερώθηκε', course:'Μάθημα', institution:'Ίδρυμα', supervisor:'Επόπτης', team:'Ομάδα', description:'Περιγραφή', replay_tutorial:'Επανάληψη εκμάθησης', src_heat:'Θερμική ανάλυση (GeoServer WMS — Z_GIS PLUS Salzburg)', src_boundaries:'Όρια (GeoServer WFS — Z_GIS PLUS Salzburg)', src_landuse:'Χρήση γης & βλάστηση (Copernicus / EEA)', src_stats:'Στατιστικά & καιρός', src_ai:'Υποστήριξη AI', src_libs:'Βιβλιοθήκες & εργαλεία'},
};

APP.XML_META = {
  lst:   { t:'Land Surface Temperature (LST) 2022 & 2025', s:'Landsat 8 Band 10 - Google Earth Engine / Z_GIS', a:'Mean LST for summer months (May-September) averaged over 2022 and 2025. Resolution 100m. Calculated from Landsat 8 TIRS Band 10.', crs:'EPSG:4326' },
  uhi:   { t:'Urban Heat Island Index (UHI) 2022 & 2025',  s:'Derived from LST - Z_GIS PLUS Salzburg',          a:'UHI = (LST - LST_mean) / LST_std. Indicates thermal deviation from the regional mean.',                                       crs:'EPSG:4326' },
  utfvi: { t:'Urban Thermal Field Variance Index (UTFVI)', s:'Derived from LST - Z_GIS PLUS Salzburg',          a:'UTFVI = (LST - LST_mean) / LST. Classes: None <0, Weak 0-0.005, Middle, Strong, Stronger, Strongest >0.020.',              crs:'EPSG:4326' },
  n2k:   { t:'Natura 2000 Protected Areas',                s:'European Environment Agency (EEA)',               a:'Natura 2000 network under the Birds Directive and Habitats Directive. Placeholder until real layer connected.', crs:'EPSG:4326' },
  gbif:  { t:'Species Occurrence Density (Plantae, Salzburg)', s:'GBIF / Haus der Natur Salzburg, via GeoServer ipsdi_st26', a:'Plantae occurrence points for the Salzburg study area. Currently available for Salzburg only; other cities pending.', crs:'EPSG:4326' },
  trees: { t:'Urban Street Trees 2018',                    s:'Copernicus Urban Atlas Street Tree Layer',        a:'DOI: 10.2909/205691b3-7ae9-41dd-abf1-1fbf60d72c8c',                                                                        crs:'EPSG:3035' },
  green: { t:'Urban Green Spaces',                         s:'Copernicus Urban Atlas 2018',                     a:'Green space coverage from Urban Atlas land use categories. Placeholder until real layer connected.', crs:'EPSG:4326' },
  lu:    { t:'Urban Atlas Land Use 2018',                  s:'Copernicus Urban Atlas',                          a:'DOI: 10.2909/fb4dffa1-6ceb-4cc0-8372-1ed354c285e6',                                                                        crs:'EPSG:3035' },
  imp:   { t:'Imperviousness Density 2021 (10m)',          s:'Copernicus HRL Imperviousness',                   a:'DOI: 10.2909/34ef6334-d432-4041-a3da-67e156d6501d',                                                                        crs:'EPSG:3035' },
  study: { t:'Study Area Boundaries',                      s:'GeoServer: ipsdi_st26:study_area',               a:'Study area boundaries per CIVIS city.',                                                                                       crs:'EPSG:4326' },
  nuts:  { t:'NUTS3 Administrative Boundaries 2021',       s:'GeoServer: ipsdi_st26:civis_nuts',               a:'NUTS Level 3 boundaries for the 11 CIVIS alliance cities.',                                                                    crs:'EPSG:4326' },
};